# -*- coding: utf-8 -*-
"""Unidad_1_C2_Python_Programming_caso_practico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8S2P5y67tU62LJqPbB6RgJG9Qck6Xw2

**Caso práctico 1**

**Objetivos:**

1. Demostrar familiaridad con el entorno de desarrollo Anaconda + Jupyter, en mi caso continuare usando Google Colab el cual tambien usa el entorno Jupyter.

# Leccion de Python 1

# **Convertidor de temperatura**
"""

# Convertidor_de_temperatura: De Celsius a Fahrenheit
celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = (9/5) * celsius + 32
print(f"The temperature in Fahrenheit is: {fahrenheit}")

"""# **Numeros pares y multiplos de tres**"""

# Este algoritmo revisa si un número es par o multiplo de tres.
number = int(input("Ingrese un número: "))

if number % 2 == 0:
    print(f"El número {number} es par.")
else:
    print(f"El número {number} es impar.")
    if number % 3 == 0:
        print(f"El número {number} es también, multiplo de tres.")

"""# **Verificar contraseña**


"""

# Verificador de contraseña
password = input("Introduce tu password: ")

if password == "python1234":
    print("Password correcto")
else:
    print("Acceso denegado, Password incorrecto")

"""# **Calculadora de descuento**"""

# Calculadora de descuento
precio_original = float(input("Introduzca el precion original del producto: "))
porcentaje_descuento = float(input("Introduzca el porcentaje de descuento: "))

cantidad_descuento = (porcentaje_descuento / 100) * precio_original
precio_final = precio_original - cantidad_descuento

print(f"Cantidad descuento: {cantidad_descuento}")
print(f"Precio final despues de descuento: {precio_final}")