# -*- coding: utf-8 -*-
"""Unidad_1_C2_Python_Programming_caso_practico_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-8dutUNh5lat5z06Cb_ajt7umQcpGZY

**Caso práctico 1**

**Objetivos:**

1. En esta unidad, llevaremos a cabo tres ejercicios en las que aplicaremos integralmente los conocimientos adquiridos recientemente, así como los aprendidos en unidades previas. Al concluir estas prácticas, se espera que el estudiante consolide su entendimiento sobre estructuras de datos, bucles y entrada y salida de ficheros.

# Leccion de Python 1

# **Contador de ocurrencias de "Sancho" y "Dulcinea"**
"""

file_path = '/content/drive/MyDrive/Colab Notebooks/Python programming material/quijote.txt'

# Contador de ocurrencias de "Sancho" y "Dulcinea"
with open(file_path, 'r') as file:
    text = file.read().lower()

sancho_count = text.count('sancho')
dulcinea_count = text.count('dulcinea')

print(f"'Sancho' aparece {sancho_count} veces.")
print(f"'Dulcinea' aparece {dulcinea_count} veces.")

"""# **Reescribir Don Quijote con un nuevo nombre**"""

new_file_path = '/content/drive/MyDrive/Colab Notebooks/Python programming material/manolito.txt'

# Reemplace "Don Quijote" con "Manolito"
with open(file_path, 'r') as file:
    new_text_lines = [line.replace('Don Quijote', 'Manolito') for line in file]

with open(new_file_path, 'w') as new_file:
    new_file.writelines(new_text_lines)

print(f"Nuevo archivo guardado en {new_file_path}")

"""# **Contador de palabras**


"""

from collections import Counter

# Cuenta la cantidad de ocurrencias por palabra
with open(file_path, 'r') as file:
    words = file.read().lower().split()

word_count = Counter(words)

# Palabras que se repiten mas de 100 veces
frequent_words = {word: count for word, count in word_count.items() if count > 100}
print(f"Palabras que se repiten mas de 100 veces: {frequent_words}")

"""# **Administrador de usuario**"""

# Registro de usuario
import json

user_file_path = '/content/drive/MyDrive/Colab Notebooks/Python programming material/users.json'

users = {}
while True:
    username = input("Ingrese nombre (o 'SALIR' para finalizar): ")
    if username == 'SALIR':
        break
    password = input("Ingrese contraseña: ")
    users[username] = password

# Save to JSON
with open(user_file_path, 'w') as file:
    json.dump(users, file)

print(f"Datos de usuario registrados y guardados en {user_file_path}")

"""# **Mostrar usuarios registrados**"""

# Cargue y muestre usuarios
with open(user_file_path, 'r') as file:
    users = json.load(file)

print("Usuarios registrados:")
for username in users.keys():
    print(username)

usernames_list = [username for username in users.keys()]
print("Lista de usuarios:", usernames_list)

"""# **Sistema de inicio**"""

# Sistema de inicio
with open(user_file_path, 'r') as file:
    users = json.load(file)

for attempt in range(3, 0, -1):
    username = input("Ingrese usuario: ")
    password = input("Ingrese contraseña: ")

    if users.get(username) == password:
        print("Bienvenido!")
        break
    else:
        print(f"Credenciales invalidas. Intentos restantes: {attempt-1}")
else:
    print("Acceso denegado.")

"""# **Ventas**"""

import csv

sales_file_path = '/content/drive/MyDrive/Colab Notebooks/Python programming material/ventas.csv'

# Calcular las ventas totales
total_sales = 0
with open(sales_file_path, 'r') as file:
    csv_reader = csv.reader(file)
    next(csv_reader)  # Saltar encabezado, no se necesita.
    for row in csv_reader:
        total_sales += float(row[4])  # Columna 5 es el "total"

print(f"Ventas totales: {total_sales}")

"""# **Total ventas solo camisetas**"""

# Filter T-shirt sales
tshirt_sales_file_path = '/content/drive/MyDrive/Colab Notebooks/Python programming material/tshirt_sales.csv'

with open(sales_file_path, 'r') as file:
    csv_reader = csv.reader(file)
    header = next(csv_reader)  # Incluyendo encabezado en este caso
    tshirt_sales = [row for row in csv_reader if row[1].lower() == 'camiseta']

# Escribe ventas de camisetas en un nuevo archivo
with open(tshirt_sales_file_path, 'w') as file:
    csv_writer = csv.writer(file)
    csv_writer.writerow(header)  # Escribiendo encabezado
    csv_writer.writerows(tshirt_sales)

print(f"Total ventas camisetas guardadas en {tshirt_sales_file_path}")

"""# **Producto mas costoso**"""

# Encontremos el producto mas costoso
producto_mas_costoso = ('', 0)  # (nombre producto, precio)

with open(sales_file_path, 'r') as file:
    csv_reader = csv.reader(file)
    next(csv_reader)
    for row in csv_reader:
        producto, precio_unidad = row[1], float(row[3])  # Columna 2 es "producto", Column 4 es "precio_unidad"
        if precio_unidad > producto_mas_costoso[1]:
            producto_mas_costoso = (producto, precio_unidad)

print(f"producto mas costoso: {producto_mas_costoso[0]} a ${producto_mas_costoso[1]}")